[tool.poetry]
name = "location_ipfire_db_reader"
version = "1.0.0"
description = "Easily get the country code from an ip address."
authors = ["Steven Van Ingelgem <steven@vaningelgem.be>"]
license = "MIT"
readme = "README.md"
packages = [{include = "location_ipfire_db_reader"}]


[tool.poetry.dependencies]
python = ">=3.6"
requests = ">=2"


[tool.poetry.group.dev.dependencies]
black = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line_length = 120
