[project]
name = "location_ipfire_db_reader"
version = "1.0.7"
description = "Easily get the country code from an ip address."
authors = [{ name = "Steven Van Ingelgem", email = "steven@vaningelgem.be" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["requests>=2"]

[project.urls]
"Source Code" = "https://github.com/svaningelgem/location_ipfire_db_reader"

[dependency-groups]
dev = [
    "ruff",
    "pytest-cov",
    "pytest-mock",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"


[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = [
    "if typing.TYPE_CHECKING:"
]


[tool.ruff]
fix = true

# Same as Black.
line-length = 120

target-version = "py39"

[tool.ruff.lint]
select = [
    "ANN", # flake8-annotations
    "B", # flake8-bugbear
    "C90", # mccabe
    "C4", # flake8-comprehensions
    # "D", # flake8-docstrings
    "D213", # Augment NumPy docstring convention: Multi-line docstring summary should start at the second line
    "D417", # Augment NumPy docstring convention: Missing argument descriptions
    "E", # pycodestyle
    "EM", # flake8-errmsg
    "F", # Pyflakes
    "FA", # flake8-future-annotations
    "FBT001", # flake8-boolean-trap
    "I", # isort
    "PIE", # flake8-pie
    "PT", # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "TD", # flake8-todos
    "TID", # flake8-tidy-imports
    "TRY", # tryceratops
    "UP", # pyupgrade
    "W", # pycodestyle
]
ignore = [
    "D211",
    "D213",
    "ANN001",  # Missing type annotation for function argument `self`
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
